from django.urls import path
from . import views
urlpatterns = [
    path('events/', views.getEvents, name='getEvents'),
    path('events/<int:eventID>/', views.getEvent, name='getEvent'),
    path('events/<int:creator_id>/creator_id/', views.getEventByCreatorId, name='getEventByCreatorId'),
    path('events/create/', views.createEvent, name='createEvent'),
    path('events/<int:eventID>/update/', views.updateEvent, name='updateEvent'),
    path('events/<int:eventID>/delete/', views.deleteEvent, name='deleteEvent'),
    path('events/<int:eventID>/register/', views.registerStudent, name='registerStudent'),
    path('events/<int:eventID>/unregister/', views.unregisterStudent, name='unregisterStudent'),
    path('events/<int:eventID>/registered_students/', views.getRegisteredStudents, name='getRegisteredStudents'),
    path('events/full/', views.getFullEvents, name='getFullEvents'),
    path('events/available/', views.getAvailableEvents, name='getAvailableEvents'),
    path('events/sorted_by_creation_date/', views.getEventsSortedByCreationDate, name='getEventsSortedByCreationDate'),
    path('events/sorted_by_update_date/', views.getEventsSortedByUpdateDate, name='getEventsSortedByUpdateDate'),
    path('events/sorted_by_start_date/', views.getEventsSortedByStartDate, name='getEventsSortedByStartDate'),
    path('events/sorted_by_end_date/', views.getEventsSortedByEndDate, name='getEventsSortedByEndDate'),
    path('events/filters/', views.getEventsByMultipleFilters, name='getEventsByMultipleFilters'),
    path('', views.apiOverview, name='apiOverview'),
    path('events/count/', views.getEventCount, name='getEventCount'),
    path('events/upcoming/', views.getUpcomingEvents, name='getUpcomingEvents'),
    path('events/past/', views.getPastEvents, name='getPastEvents'),
    path('events/search/', views.searchEvents, name='searchEvents'),
    path('events/by_host/<str:hosted_by>/', views.getEventsByHost, name='getEventsByHost'),
    path('events/by_type/<str:eventType>/', views.getEventsByType, name='getEventsByType'),
    path('events/by_location/<str:location>/', views.getEventsByLocation, name='getEventsByLocation'),
    path('events/by_creator/<str:creator>/', views.getEventsByCreator, name='getEventsByCreator'),
    path('events/by_date_range/', views.getEventsByDateRange, name='getEventsByDateRange'),
    path('events/by_capacity/<int:min_capacity>/', views.getEventsByCapacity, name='getEventsByCapacity'),
    path('events/recent/<int:days>/', views.getRecentEvents, name='getRecentEvents'),
    path('events/with_links/', views.getEventsWithLinks, name='getEventsWithLinks'),
    path('events/with_zoom_links/', views.getEventsWithZoomLinks, name='getEventsWithZoomLinks'),
    path('events/by_keyword/', views.getEventsByKeyword, name='getEventsByKeyword'),
    path('health/', views.healthCheck, name='healthCheck'),
    path('info/', views.apiInfo, name='apiInfo'),
    path('welcome/', views.welcome, name='welcome'),
]
