# Generated by Django 5.2.8 on 2025-11-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('zoom_link', models.URLField(blank=True, null=True)),
                ('hosted_by', models.CharField(max_length=100)),
                ('registered_students', models.JSONField(default=list)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
