# Generated by Django 5.2.8 on 2025-11-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
